/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface CropAdjust {
  'rotation' : number,
  'zoom' : number,
  'offsetX' : number,
  'offsetY' : number,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Greeting {
  'subtext' : string,
  'headline' : string,
  'heroCrop' : [] | [CropAdjust],
  'heroPhoto' : [] | [StoredFile],
}
export interface GreetingInput { 'subtext' : string, 'headline' : string }
export interface Message {
  'id' : MessageId,
  'crop' : [] | [CropAdjust],
  'text' : string,
  'photo' : [] | [StoredFile],
  'position' : bigint,
}
export type MessageId = bigint;
export interface MessageInput {
  'crop' : [] | [CropAdjust],
  'text' : string,
  'photo' : [] | [StoredFile],
  'position' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface SiteContent {
  'messages' : Array<Message>,
  'song' : [] | [StoredFile],
  'greeting' : Greeting,
  'songSource' : SongSource,
}
export interface SongSource {
  'url' : [] | [string],
  'file' : [] | [StoredFile],
  'kind' : SongSourceKind,
}
export type SongSourceKind = { 'url' : null } |
  { 'upload' : null } |
  { 'default' : null };
export type StoredFile = Uint8Array;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Owner-only: add a message entry.
   */
  'addMessage' : ActorMethod<[MessageInput], MessageId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Owner-only: clear the external audio URL, reverting to the uploaded song.
   */
  'clearSongUrl' : ActorMethod<[], SongSource>,
  /**
   * / Owner-only: delete a message entry.
   */
  'deleteMessage' : ActorMethod<[MessageId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Returns static Markdown documentation for this backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Public read of all site content.
   */
  'getSiteContent' : ActorMethod<[], SiteContent>,
  /**
   * / Public read of the active background song source.
   */
  'getSongSource' : ActorMethod<[], SongSource>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Owner-only: save crop/adjust parameters for the hero photo.
   */
  'setHeroCrop' : ActorMethod<[CropAdjust], boolean>,
  /**
   * / Owner-only: set or replace the hero photo.
   */
  'setHeroPhoto' : ActorMethod<[StoredFile], Greeting>,
  /**
   * / Owner-only: save crop/adjust parameters for a message's photo.
   */
  'setMessageCrop' : ActorMethod<[MessageId, CropAdjust], boolean>,
  /**
   * / Owner-only: set or replace the background song.
   */
  'setSong' : ActorMethod<[StoredFile], StoredFile>,
  /**
   * / Owner-only: set the external audio URL for the background song.
   */
  'setSongUrl' : ActorMethod<[string], SongSource>,
  /**
   * / Owner-only: update the greeting headline and subtext.
   */
  'updateGreeting' : ActorMethod<[GreetingInput], Greeting>,
  /**
   * / Owner-only: update a message entry.
   */
  'updateMessage' : ActorMethod<[MessageId, MessageInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];