/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const CropAdjust = IDL.Record({
  'rotation' : IDL.Float64,
  'zoom' : IDL.Float64,
  'offsetX' : IDL.Float64,
  'offsetY' : IDL.Float64,
});
export const StoredFile = IDL.Vec(IDL.Nat8);
export const MessageInput = IDL.Record({
  'crop' : IDL.Opt(CropAdjust),
  'text' : IDL.Text,
  'photo' : IDL.Opt(StoredFile),
  'position' : IDL.Nat,
});
export const MessageId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SongSourceKind = IDL.Variant({
  'url' : IDL.Null,
  'upload' : IDL.Null,
  'default' : IDL.Null,
});
export const SongSource = IDL.Record({
  'url' : IDL.Opt(IDL.Text),
  'file' : IDL.Opt(StoredFile),
  'kind' : SongSourceKind,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Message = IDL.Record({
  'id' : MessageId,
  'crop' : IDL.Opt(CropAdjust),
  'text' : IDL.Text,
  'photo' : IDL.Opt(StoredFile),
  'position' : IDL.Nat,
});
export const Greeting = IDL.Record({
  'subtext' : IDL.Text,
  'headline' : IDL.Text,
  'heroCrop' : IDL.Opt(CropAdjust),
  'heroPhoto' : IDL.Opt(StoredFile),
});
export const SiteContent = IDL.Record({
  'messages' : IDL.Vec(Message),
  'song' : IDL.Opt(StoredFile),
  'greeting' : Greeting,
  'songSource' : SongSource,
});
export const GreetingInput = IDL.Record({
  'subtext' : IDL.Text,
  'headline' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addMessage' : IDL.Func([MessageInput], [MessageId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearSongUrl' : IDL.Func([], [SongSource], []),
  'deleteMessage' : IDL.Func([MessageId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
  'getSongSource' : IDL.Func([], [SongSource], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setHeroCrop' : IDL.Func([CropAdjust], [IDL.Bool], []),
  'setHeroPhoto' : IDL.Func([StoredFile], [Greeting], []),
  'setMessageCrop' : IDL.Func([MessageId, CropAdjust], [IDL.Bool], []),
  'setSong' : IDL.Func([StoredFile], [StoredFile], []),
  'setSongUrl' : IDL.Func([IDL.Text], [SongSource], []),
  'updateGreeting' : IDL.Func([GreetingInput], [Greeting], []),
  'updateMessage' : IDL.Func([MessageId, MessageInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const CropAdjust = IDL.Record({
    'rotation' : IDL.Float64,
    'zoom' : IDL.Float64,
    'offsetX' : IDL.Float64,
    'offsetY' : IDL.Float64,
  });
  const StoredFile = IDL.Vec(IDL.Nat8);
  const MessageInput = IDL.Record({
    'crop' : IDL.Opt(CropAdjust),
    'text' : IDL.Text,
    'photo' : IDL.Opt(StoredFile),
    'position' : IDL.Nat,
  });
  const MessageId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SongSourceKind = IDL.Variant({
    'url' : IDL.Null,
    'upload' : IDL.Null,
    'default' : IDL.Null,
  });
  const SongSource = IDL.Record({
    'url' : IDL.Opt(IDL.Text),
    'file' : IDL.Opt(StoredFile),
    'kind' : SongSourceKind,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'crop' : IDL.Opt(CropAdjust),
    'text' : IDL.Text,
    'photo' : IDL.Opt(StoredFile),
    'position' : IDL.Nat,
  });
  const Greeting = IDL.Record({
    'subtext' : IDL.Text,
    'headline' : IDL.Text,
    'heroCrop' : IDL.Opt(CropAdjust),
    'heroPhoto' : IDL.Opt(StoredFile),
  });
  const SiteContent = IDL.Record({
    'messages' : IDL.Vec(Message),
    'song' : IDL.Opt(StoredFile),
    'greeting' : Greeting,
    'songSource' : SongSource,
  });
  const GreetingInput = IDL.Record({
    'subtext' : IDL.Text,
    'headline' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addMessage' : IDL.Func([MessageInput], [MessageId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearSongUrl' : IDL.Func([], [SongSource], []),
    'deleteMessage' : IDL.Func([MessageId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
    'getSongSource' : IDL.Func([], [SongSource], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setHeroCrop' : IDL.Func([CropAdjust], [IDL.Bool], []),
    'setHeroPhoto' : IDL.Func([StoredFile], [Greeting], []),
    'setMessageCrop' : IDL.Func([MessageId, CropAdjust], [IDL.Bool], []),
    'setSong' : IDL.Func([StoredFile], [StoredFile], []),
    'setSongUrl' : IDL.Func([IDL.Text], [SongSource], []),
    'updateGreeting' : IDL.Func([GreetingInput], [Greeting], []),
    'updateMessage' : IDL.Func([MessageId, MessageInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };